// <auto-generated />
using System;
using ATMDotNetCoreApp.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATMDotNetCoreApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129170230_atm1")]
    partial class atm1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATMDotNetCoreApp.Models.AtmTransactionModel", b =>
                {
                    b.Property<int>("TransacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransacId"));

                    b.Property<int>("AccNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfTrans")
                        .HasColumnType("datetime2");

                    b.Property<double>("TransacAmt")
                        .HasColumnType("float");

                    b.Property<int>("TransacNo")
                        .HasColumnType("int");

                    b.Property<int>("TransacType")
                        .HasColumnType("int");

                    b.Property<int>("TransferToAccNo")
                        .HasColumnType("int");

                    b.HasKey("TransacId");

                    b.ToTable("TblAtmTransaction", (string)null);
                });

            modelBuilder.Entity("ATMDotNetCoreApp.Models.LoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccIsActive")
                        .HasColumnType("int");

                    b.Property<int>("AccNo")
                        .HasColumnType("int");

                    b.Property<string>("ActName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActPin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblLoginMaster", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
